<?php

namespace App\Models;

use App\Scopes\User\UserScope;
use Illuminate\Database\Eloquent\Model;

class Osc extends Model
{
    protected $fillable = [
        'user_id',
        'nome_fantasia',
        'cnae',
        'responsavel_legal',
        'sigla_osc',
        'ano_fundacao',
        'telefone',
        'site',
        'email',
        'ano_inscricao_cnpj',
        'situacao_imovel',
        'atividade_economica',
        'area_atuacao',
        'sub_area1',
        'sub_area2'];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new UserScope());
    }

    public function projetos(){
        return $this->hasMany(Projeto::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function banco(){
        return $this->belongsTo(Banco::class,'banco_doacao_id')->first();
    }

    public function endereco(){
        return $this->belongsTo(Endereco::class)->first();
    }

    public function metas(){
        return $this->hasMany(Osc_Metas::class)->get();
    }


}
