<?php

namespace App\Models;

use App\Scopes\Osc\OscScope;
use App\Scopes\User\UserScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Projeto extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'user_id',
        'descricao',
        'imagem',
        'instancia',
        'ambito',
        'num_registro1',
        'num_registro2',
        'segmento_cultural',
        'objetivo_geral',
        'objetivos_esp',
        'justificativa',
        'publico_alvo',
        'impactos_esperados',
        'artigo',
        'valor_meta'
    ];

//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::addGlobalScope(new OscScope());
//    }


    public function osc(){
        return $this->belongsTo(Osc::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function proponente(){
        return $this->belongsTo(Pessoa::class)->first();
    }

    public function bancoPatrocinio(){
        return $this->belongsTo(Banco::class,'banco_patrocinio_id')->first();
    }
    public function bancoDoacao(){
        return $this->belongsTo(Banco::class,'banco_doacao_id')->first();
    }
}
